BREED_BASELINES = [
    {
        "id": "golden_retriever",
        "displayName": "Golden Retriever",
        "species": "dog",
        "weightKg": 28.5,
        "neckGirthCm": 42.0,
        "chestGirthCm": 68.0,
        "backLengthCm": 55.0,
    },
    {
        "id": "labrador_retriever",
        "displayName": "Labrador Retriever",
        "species": "dog",
        "weightKg": 30.0,
        "neckGirthCm": 44.0,
        "chestGirthCm": 70.0,
        "backLengthCm": 56.0,
    },
    {
        "id": "french_bulldog",
        "displayName": "French Bulldog",
        "species": "dog",
        "weightKg": 12.0,
        "neckGirthCm": 34.0,
        "chestGirthCm": 50.0,
        "backLengthCm": 32.0,
    },
    {
        "id": "german_shepherd",
        "displayName": "German Shepherd",
        "species": "dog",
        "weightKg": 34.0,
        "neckGirthCm": 46.0,
        "chestGirthCm": 78.0,
        "backLengthCm": 62.0,
    },
    {
        "id": "poodle",
        "displayName": "Poodle",
        "species": "dog",
        "weightKg": 24.0,
        "neckGirthCm": 38.0,
        "chestGirthCm": 60.0,
        "backLengthCm": 45.0,
    },
    {
        "id": "bulldog",
        "displayName": "Bulldog",
        "species": "dog",
        "weightKg": 23.0,
        "neckGirthCm": 42.0,
        "chestGirthCm": 66.0,
        "backLengthCm": 40.0,
    },
    {
        "id": "beagle",
        "displayName": "Beagle",
        "species": "dog",
        "weightKg": 11.0,
        "neckGirthCm": 30.0,
        "chestGirthCm": 45.0,
        "backLengthCm": 34.0,
    },
    {
        "id": "rottweiler",
        "displayName": "Rottweiler",
        "species": "dog",
        "weightKg": 46.0,
        "neckGirthCm": 52.0,
        "chestGirthCm": 86.0,
        "backLengthCm": 66.0,
    },
    {
        "id": "yorkshire_terrier",
        "displayName": "Yorkshire Terrier",
        "species": "dog",
        "weightKg": 3.2,
        "neckGirthCm": 20.0,
        "chestGirthCm": 28.0,
        "backLengthCm": 22.0,
    },
    {
        "id": "dachshund",
        "displayName": "Dachshund",
        "species": "dog",
        "weightKg": 8.5,
        "neckGirthCm": 27.0,
        "chestGirthCm": 38.0,
        "backLengthCm": 35.0,
    },
    {
        "id": "boxer",
        "displayName": "Boxer",
        "species": "dog",
        "weightKg": 29.0,
        "neckGirthCm": 43.0,
        "chestGirthCm": 72.0,
        "backLengthCm": 55.0,
    },
    {
        "id": "siberian_husky",
        "displayName": "Siberian Husky",
        "species": "dog",
        "weightKg": 24.0,
        "neckGirthCm": 40.0,
        "chestGirthCm": 64.0,
        "backLengthCm": 52.0,
    },
    {
        "id": "chihuahua",
        "displayName": "Chihuahua",
        "species": "dog",
        "weightKg": 2.5,
        "neckGirthCm": 18.0,
        "chestGirthCm": 25.0,
        "backLengthCm": 18.0,
    },
    {
        "id": "pomeranian",
        "displayName": "Pomeranian",
        "species": "dog",
        "weightKg": 3.0,
        "neckGirthCm": 21.0,
        "chestGirthCm": 30.0,
        "backLengthCm": 21.0,
    },
    {
        "id": "shih_tzu",
        "displayName": "Shih Tzu",
        "species": "dog",
        "weightKg": 6.5,
        "neckGirthCm": 24.0,
        "chestGirthCm": 36.0,
        "backLengthCm": 26.0,
    },
    {
        "id": "corgi",
        "displayName": "Corgi",
        "species": "dog",
        "weightKg": 12.5,
        "neckGirthCm": 31.0,
        "chestGirthCm": 48.0,
        "backLengthCm": 38.0,
    },
    {
        "id": "border_collie",
        "displayName": "Border Collie",
        "species": "dog",
        "weightKg": 18.0,
        "neckGirthCm": 36.0,
        "chestGirthCm": 58.0,
        "backLengthCm": 48.0,
    },
    {
        "id": "australian_shepherd",
        "displayName": "Australian Shepherd",
        "species": "dog",
        "weightKg": 24.0,
        "neckGirthCm": 40.0,
        "chestGirthCm": 63.0,
        "backLengthCm": 50.0,
    },
    {
        "id": "cavalier_king_charles_spaniel",
        "displayName": "Cavalier King Charles Spaniel",
        "species": "dog",
        "weightKg": 7.0,
        "neckGirthCm": 25.0,
        "chestGirthCm": 37.0,
        "backLengthCm": 28.0,
    },
    {
        "id": "cocker_spaniel",
        "displayName": "Cocker Spaniel",
        "species": "dog",
        "weightKg": 13.5,
        "neckGirthCm": 32.0,
        "chestGirthCm": 48.0,
        "backLengthCm": 37.0,
    },
    {
        "id": "jack_russell_terrier",
        "displayName": "Jack Russell Terrier",
        "species": "dog",
        "weightKg": 7.0,
        "neckGirthCm": 26.0,
        "chestGirthCm": 40.0,
        "backLengthCm": 30.0,
    },
]


BREED_BASELINE_BY_ID = {item["id"]: item for item in BREED_BASELINES}
